#!/usr/bin/env bash
shopt -s extglob

# vars
project='google-daemon'
version=$( grep 'Version:' SPECS/${project}.spec | egrep -o '([[:digit:]].+)' )
release=$( grep 'Release:' SPECS/${project}.spec | egrep -o '([[:digit:]]+)' )

cd ~/rpmbuild

# cleanup
rm -fr results
rm -f SOURCES/!(*.patch)
rm -f SRPMS/*

# get sources
# note: spectool is smart and it will skip successful downloads only if you do not clean them up (above).
cd SOURCES
spectool -g ../SPECS/${project}.spec
cd ..

# generate SRPM
rpmbuild -bs SPECS/${project}.spec

# try to build
mock --no-cleanup-after --resultdir results/ --rebuild SRPMS/${project}-${version}-${release}.fc20.src.rpm

exit 0
