#!/usr/bin/env bash

# vars
project='hhvm'
version=$( grep 'Version:' SPECS/hhvm.spec | egrep -o '([[:digit:]].+)' )
release=$( grep 'Release:' SPECS/hhvm.spec | egrep -o '([[:digit:]]+)' )

cd ~/rpmbuild

# get sources
# note: spectool is smart and it will skip successful downloads.
cd SOURCES
spectool -g ../SPECS/hhvm.spec
cd ..

# generate SRPM
rpmbuild -bs SPECS/hhvm.spec

# try to build
mock --resultdir results/ --rebuild SRPMS/hhvm-${version}-${release}.fc20.src.rpm

exit 0
