#!/usr/bin/env bash

# vars
version=$( grep 'Version:' SPECS/hhvm.spec | egrep -o '([[:digit:]].+)' )
release=$( grep 'Release:' SPECS/hhvm.spec | egrep -o '([[:digit:]]+)' )

cd ~/rpmbuild

# obtener fuentes (solo una vez; o cuando cambiemos de versión)
# cd SOURCES
# spectool -g ../SPECS/hhvm.spec
# cd ..

# generar SRPM
rpmbuild -bs SPECS/hhvm.spec

# probar el build
mock --resultdir results/ --rebuild SRPMS/hhvm-${version}-${release}.fc20.src.rpm

# alternativamente, corre los dos en una línea
# rpmbuild -bs SPECS/hhvm.spec; mock --resultdir results/ --rebuild SRPMS/hhvm-${version}-${release}.fc20.src.rpm

exit 0
