#!/usr/bin/env bash

#
## vars

# paths
home=${HOME}
src_path="${home}/src/non/daw"
rpmbuild_path="${home}/rpmbuild"

# package
package='non'
version='v1.1.0'
release='1'

#
## Procedure

# get source code
cd $src_path
git pull

# export source code
git archive --prefix="${package}-${version}/" -o ${rpmbuild_path}/SOURCES/${package}-${version}.tar  master
xz --force ${rpmbuild_path}/SOURCES/${package}-${version}.tar

# package
rpmbuild -bs ${rpmbuild_path}/SPECS/${package}.spec

# build
mock --resultdir=${rpmbuild_path}/results --rebuild  ${rpmbuild_path}/SRPMS/${package}-${version}-${release}.fc17.src.rpm

# cleanup


exit 0
